# Generated by Django 6.0.6 on 2026-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('na_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eu_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('jp_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('other_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('global_sales', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
